### ISSUE TITLE
TODO list for stacked images analysis

### ISSUE THREAD

**Issue by ipashchenko** [ipashchenko/ve#1]
- [x] Angle scale (colorbar) in degrees.

- [x] Add error maps of fractional polarization.

- [x] Use proper HDI for polarization flux and fractional polarization (asymmetric?).

- [x] Draw errors of PPOL, PANG and FPOL on top of the PPOL contours and plot only first IPOL contour.
